name: Deploy Jekyll site to Azure Storage

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (needed for PostCSS)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install project dependencies (including PostCSS)
      run: |
        npm install postcss postcss-cli

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install Jekyll dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build --trace

    - name: Upload with Azure CLI
      run: |
        az storage blob upload-batch --destination ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} --source ./_site --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}    