name: Deploy Jekyll site to Azure Storage

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (needed for PostCSS)
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use latest LTS version

    - name: Install PostCSS dependencies
      run: |
        npm install -g postcss postcss-cli
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build

    - name: Upload to Azure Storage
      uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      with:
        connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        container-name: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
        source-folder: './_site'
